version: "3.9"
services:
  blog-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      mysql_users_username: 'root'
      mysql_users_password: 'root'
      mysql_users_host: '127.0.0.1:3306'
      mysql_users_schema: 'db'
    ports:
      - "3000:3000"
    links:
      - blog-api-db
  blog-api-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
