version: "3.9"
services:
  blog-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      mysql_users_username: 'user'
      mysql_users_password: 'user'
      mysql_users_host: 'db'
      mysql_users_schema: 'db'
    ports:
      - "3000:3000"
    links:
      - blog-api-db
  blog-api-db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
